apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argo-pv-claim2
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi