apiVersion: v1
kind: PersistentVolume
metadata:
  name: argo-pv-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: host_mnt/C/Users/jstranig/bidon